from models import VacuumCleaner, Television, WashingMachine, MusicCenter, TapeRecorder, RadioReceiver

bosh = MusicCenter.MusicCenter("Music center", 400, 25, 1, 40)
print(bosh.get_music_center())
print(str(bosh))
samsung = WashingMachine.WashingMachine("Washing machine", 500, 66, 9)
print(samsung.get_washing_machine())
philips = VacuumCleaner.VacuumCleaner("Vacuum cleaner", 70, 4, False)
print(philips.get_vacuum_cleaner())
kivi = Television.Television("TV", 60, 8, 43)
print(kivi.get_television())
giradischi = TapeRecorder.TapeRecorder("Tape recorder", 25, 2, 50)
print(giradischi.get_radio_receiver())
okord = RadioReceiver.RadioReceiver("Radio receiver", 20, 3, 20)
print(okord.get_radio_receiver())
